//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETMATHANG_BACKLOG
    {
        public string IDCTMH { get; set; }
        public string IDMatHang { get; set; }
        public string Size { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual MATHANG_BACKLOG MATHANG_BACKLOG { get; set; }
    }
}
