//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANG_BACKLOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATHANG_BACKLOG()
        {
            this.CHITIETMATHANG_BACKLOG = new HashSet<CHITIETMATHANG_BACKLOG>();
        }
    
        public string IDMATHANG { get; set; }
        public string TenMH { get; set; }
        public string IDLoaiHang { get; set; }
        public string IDSubLoaiHang { get; set; }
        public string URLHinhAnh1 { get; set; }
        public string URLHinhAnh2 { get; set; }
        public string URLHinhAnh3 { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> GiaMoi { get; set; }
        public Nullable<int> GiaCu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETMATHANG_BACKLOG> CHITIETMATHANG_BACKLOG { get; set; }
    }
}
